# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nJdH4VI0Pi8wsOl-a1zSl2g3AXYYnT1c

1. Carregar os dados
"""

print('##### comeco em server #####')
import pandas as pd
new_data = pd.read_csv('Dataset_spine_unknown.csv')

import pickle
model = pickle.load(open('model.sav', 'rb'))

predictions = model.predict(new_data)
predictions

new_data['inferencias'] =  predictions
new_data.to_csv('resultados.csv', index = False)